### ISSUE TITLE
How to view files uploaded with gce_ssh_upload() from RStudio server

### ISSUE THREAD

**Issue by ben519** [cloudyr/googleComputeEngineR#114]
I'm confused how to use `gce_ssh_upload()` so that I can access the uploaded files from my RStudio server instance running in the browser.  Here's my setup

```
library(googleComputeEngineR)

#---- Create the VM ---------------------------------------------

# Set project scopes
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

# Define project, zone, account_key
project <- "abc"
zone <- "us-central1-a"
account_key <- file.path(getwd(), "config/abc-gce-credentials.json")

# Set environment variables
Sys.setenv(
  GCE_AUTH_FILE = account_key,
  GCE_DEFAULT_PROJECT_ID = project,
  GCE_DEFAULT_ZONE = zone
)

# Set a project name used for this R session
gce_global_project(project = project)
gce_global_zone(zone = zone)

# Authenticate
gce_auth()

# Check
default_project <- gce_get_project()
default_project

# Create VM
vm <- gce_vm(
  template = "rstudio",
  name = "rstudio-server",
  username = "bgorman",
  password = "foo",
  predefined_type = "n1-standard-1"
)

# Get the VM object
rstudioVM <- gce_vm("rstudio-server")
rstudioVM  # Use the IP address. Put this in Chrome URL to login to RStudio
```

This works and I'm able to launch and use RStudio in my browser. 

At this point, my goal is to upload a file via ssh that will be visible from the RStudio Files pane. (I can upload files through the GUI, but this is not ideal because this is a task I need to do daily for multiple files.)

<img width="793" alt="screen shot 2018-10-30 at 5 10 30 pm" src="https://user-images.githubusercontent.com/723099/47753797-d00ba880-dc66-11e8-8cbd-1fb9e2f3c7c3.png">

I've followed one of the many guides for creating ssh credentials and using them [here](https://www.youtube.com/watch?v=hh1XHhAG7-M).

Next, I create a text file on my local computer and attempt to upload it to my VM via ssh

```
# Create a simple text file to upload
writeLines("Hello World", "~/Desktop/hello_world.txt")

# Upload a simple text file
googleComputeEngineR::gce_ssh_upload(
  instance = rstudioVM, 
  local = "~/Desktop/hello_world.txt", 
  remote = "/home/bgorman/hello_world.txt", 
  username = "bgorman", 
  key.pub = "path/to/my-key.pub", 
  key.private = "path/to/my-key", 
  verbose = T
)
```

This is where things get confusing. The above `gce_ssh_upload()` works and I can see the that text file was uploaded to `/home/bgorman/`. However, the file is not accessible from the RStudio server instance. It seems RStudio is reading files from `/home/gcer/` but I get a "permission denied" error when I try to upload to that directory.

Here's what I see from the SSH shell after uploading the file..
<img width="345" alt="screen shot 2018-10-30 at 5 01 21 pm" src="https://user-images.githubusercontent.com/723099/47754052-a2732f00-dc67-11e8-9c70-980cbb22ebc0.png">

Here's what I see from RStudio server..
<img width="351" alt="screen shot 2018-10-30 at 5 00 47 pm" src="https://user-images.githubusercontent.com/723099/47754057-a8691000-dc67-11e8-8d9a-afdfbca99f4b.png">

How do I use `gce_ssh_upload()` to upload files that are accessible from RStudio server in the browser?

**Comment by MarkEdmondson1234** [comment]
Rstudio is being launched in a Docker container, so its within that container the files need to appear within.  I would urge you though to use `googleCloudStorageR` within your scripts instead of relying on the VM filesystem.  There is an article about this [on the website](https://cloudyr.github.io/googleComputeEngineR/articles/persistent-rstudio.html).

However, to answer your question you would use `googleComputeEngineR::docker_cmd()` to issue the SSH uploads rather than `gce_ssh_upload()` to upload to within the RStudio instance - something like:

```r
docker_cmd(vm, "exec", "scp -r local_file.dat username@123.323.434.54:/usr/remote_file")
```

**Comment by ben519** [comment]
Thanks Mark. Normally I'd agree with you about using `googleCloudStorageR`, although in my case it seems like overkill.

If I run your snippet: `docker_cmd(vm, "exec", "scp -r local_file.dat username@123.323.434.54:/usr/remote_file")` with a dummy file, my file gets uploaded to the server but it's still not visible within Rstudio. I feel like the target path, */usr/remote_file*, is not correct. It looks like RStudio can't see any files outside of */home/gcer/* but I can't figure out how to upload files to that path.  

(Perhaps the simplest solution really is to use `googleCloudStorageR`, although it feels like over-engineering.)

**Comment by MarkEdmondson1234** [comment]
I think its simpler to use `googleCloudStorageR`, especially as auth is taken care with via `googleAuthR::gar_gce_auth()`, the I/O speeds are very fast and file sizes infinite, and can then easily be available for other instances. 

But :)

It should be able to see any files that are uploaded to `/home/username` so it may be just that user permissions need to be set so that the RStudio user can see it? ("gcer") (perhaps just chmod 777 to confirm theory)

I'm aware using Docker to host the RStudio makes this all more complicated, and perhaps should just offer a Dockerless RStudio install from the template, even if its not what I would recommend.

**Comment by ben519** [comment]
Ended up just using `googleCloudStorageR `. Thanks again for your help Mark.
