### ISSUE TITLE
How to read/write data from cloud storage bucket in rstudio hosted on CE instance?

### ISSUE THREAD

**Issue by Arsalan9002** [cloudyr/googleComputeEngineR#117]

**Comment by MarkEdmondson1234** [comment]
I suggest the best way is to use `googleCloudStorageR` which you can authenticate via `googleAuthR::gar_gce_auth()` that will reuse the auth of your VM.

**Comment by Arsalan9002** [comment]
okay right. furthermore, kindly help me out with this confusion as well i dont understand the connection of docker with googleCloudStorageR and googleComputeEngineR

**Comment by MarkEdmondson1234** [comment]
googleComputeEngineR can create any VM as specified in the compute engine API.  The `gce_vm()` with `template="rstudio"` assumes some defaults and uses them to create a Docker based RStudio instance.  

If you want you can customise it more yourself and use `gce_vm_create()` 

`googleCloudStorageR` doesn't have much to do with Docker, its just a useful package that is often used with googleComputeEngineR, since it can reuse its authentication and you can use it to store data.  Cloud Storgae I/O is very fast and I treat it as the hard disk for your programs.

There is a lot more detail on the website:
https://cloudyr.github.io/googleComputeEngineR/articles/troubleshooting.html

**Comment by Arsalan9002** [comment]
thanks Mark
