### ISSUE TITLE
Error 137 in travis test

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleComputeEngineR#16]
https://github.com/travis-ci/travis-ci/issues/4192

**Comment by MarkEdmondson1234** [comment]
Ping @HenrikBengtsson - so it turns out travis is timing out when it tried to run a future command where that times out. (In this case due to the SSH key not being correct)  I was looking for solutions and came across a suggestion to use another package of yours, R.utils and the [`evalWithTimeout`](http://stackoverflow.com/questions/8652681/limiting-the-time-that-a-function-processes-in-an-r-for-loop).  

Is that something you would recommend?

The error I see in the log is:

``` r
Futures: Warning: Permanently added '104.199.39.1' (RSA) to the list of known hosts.
Permission denied (publickey).
...then never returns...
```

**Comment by HenrikBengtsson** [comment]
If I understand you correctly, you're using `makeClusterPSOCK()` and that fails due to missing / incorrect SSH keys when it attempt to SSH into the worker machine and eventually Travis CI says something like "no output for 10 minutes - terminating the job"?!  Is that correct?

The way I can see `makeClusterPSOCK()` could be stuck waiting "forever" is that it spawns of that SSH system command which returns (but [errors are ignored because it uses `system(..., wait = FALSE)`](https://github.com/HenrikBengtsson/future/blob/develop/R/makeClusterPSOCK.R#L221)) and in the following step it opens up a socket connection waiting for the worker to connect back.  It here that it waits forever, because the worker never got launched in the first list.

So, instead of using `R.utils::withTimeout(makeClusterPSOCK(...))`, I think you could simply use `makeClusterPSOCK(..., timeout = ...)` instead.  The default `timeout` is 30 days (sic!).  All this is borrowed from the behavior of `parallel::makePSOCKcluster()`.

**Comment by MarkEdmondson1234** [comment]
Hi @HenrikBengtsson , just confirming that that is indeed the issue. I was thinking of doing `withTimeout` but having a `timeout` parameter would be the best way to do it. Is this something you have just added?

**Comment by HenrikBengtsson** [comment]
The `timeout` argument should have been there since `makeClusterPSOCK()`
was introduced in develop. It's `makeNodePSOCK()` that actually takes this
argument.

**Comment by MarkEdmondson1234** [comment]
The 2 minute timeout works now, thanks!
