### ISSUE TITLE
Cannot add a shiny app to shiny VM

### ISSUE THREAD

**Issue by IronistM** [cloudyr/googleComputeEngineR#51]
While trying to add a shiny app to a shiny spinned GCE VM I get an error

```R
> vm <- gce_vm(name = "shiny-app", 
+              template = "shiny", 
+              predefined_type = "n1-standard-1")
VM running
> gce_shiny_addapp(instance = "shiny-app", 
+               shinyapp = 'home/Documents/Github/CampaignPlanner/AB_test/')
Error in as.environment(where) : 
  no item called "shiny-app" on the search list
```

**Comment by MarkEdmondson1234** [comment]
Try this - pass the VM object instead of string:

```r
vm <- gce_vm(name = "shiny-app", 
                         template = "shiny",               
                         predefined_type = "n1-standard-1")

gce_shiny_addapp(instance = vm, 
                               shinyapp = 'home/Documents/Github/CampaignPlanner/AB_test/')
```

**Comment by IronistM** [comment]
You are correct, now it works as expected

```R
> gce_shiny_listapps(instance = "shiny-app")
Auto-refreshing stale OAuth token.
[1] "AB_test"
```

**Comment by MarkEdmondson1234** [comment]
Ah ok, I had a go myself and I realise `gce_shiny_addapp` wasn't developed a lot as you need to add the packages the Shiny app needs, which it doesn't do yet.  I tend to install those packages and any supporting libraries in a Dockerfile instad, and follow this method for deploying Shiny apps 
https://cloudyr.github.io/googleComputeEngineR/articles/shiny-app.html

Otherwise you need to log into the instance, log into the Docker container and install the R packages yourself, which isn't so smooth as I want it to be yet.

**Comment by IronistM** [comment]
Yeah, probably the best way to go is the Dockerfile one. Will try it
tomorrow!

**Comment by MarkEdmondson1234** [comment]
Cool.  One modification to the Shiny example is to use the new Google Container registry instead to build your Docker images https://cloud.google.com/container-registry/ - you can set it up so when you push to Github it updates the Docker container /shiny app which is super handy.

**Comment by MarkEdmondson1234** [comment]
This is now much easier to work with on the github version
https://cloudyr.github.io/googleComputeEngineR/articles/shiny-app.html

You still need a Dockerfile, but the `gce_shiny_addapp` is more useful and works with the Dockerfile instead of uploading files.

**Comment by IronistM** [comment]
Thanx!
