### ISSUE TITLE
Create instance from private image

### ISSUE THREAD

**Issue by MilesAheadAlso** [cloudyr/googleComputeEngineR#73]
I've created a private image that includes all the R packages that I need for a project, even the R script. I would like to be able to run the script in your blog about [massively parallel processing](https://cloudyr.github.io/googleComputeEngineR/articles/massive-parallel.html?lipi=urn%3Ali%3Apage%3Ad_flagship3_messaging%3Bu7jVE95tRFSnoqNw8YCtxQ%3D%3D#customising-the-vms-launched).

![private_gce_image](https://user-images.githubusercontent.com/32249192/30825058-3a6a73de-a264-11e7-866d-b1d5c2e92479.JPG)

How can I modify this command to create an 8 core 30MB instance using this image?
fiftyvms <- lapply(vm_names, gce_vm, predefined_type = "n1-standard-1", template = "r-base", scheduling = preemptible)

I can easily create several instances from the gc console.

![new-gce-instance](https://user-images.githubusercontent.com/32249192/30825458-a79cb628-a265-11e7-83c7-49a2c086b6f3.JPG)

I'm sorry to ask what must seem like a mundane question, but I am very new to gc.

**Comment by MarkEdmondson1234** [comment]
Hi, no problem.  You will only need to specify the machine type to be the one you need, which in your case for an 8 core, 30GB ram instance is `n1-standard-8`:

```
fiftyvms <- lapply(vm_names, gce_vm, 
                               predefined_type = "n1-standard-8", 
                               template = "r-base", scheduling = preemptible)
```

You can see the list of machine types available to you via [`gce_list_machinetype()`](https://cloudyr.github.io/googleComputeEngineR/reference/gce_list_machinetype.html) or you can set up a custom CPU/RAM via specifying the `cpu` and `memory` arguments. 

That is quite a workload you have it you are using 50 :)  Test it, to make sure you are confident its what you need before launching it all as it will add up to some $$. 

Then to create from your image, hmm well the post uses Docker containers for this so is not the exact same.  

If you have a preexisting image on a disk, that would need to be created before hand and added to the VM on startup, which is done via the `gce_make_disk` function and supplying the `sourceImage` which is the location of your disk. I don't do this though, I use Docker so haven't come across this use case, but hopefully it should work as well.

I would look at using Docker too though, its more manageable in the long run, IMO, as instead of disk images you have Dockerfiles that can be checked into GitHub etc.

**Comment by MilesAheadAlso** [comment]
Hi Mark

It is the template with which I am struggling, not the machine type. How do
I generate a template with exactly the packages I need pre-loaded. When I
login to a VM generated using the r-base template using SSH, it does not
seem that R is installed.

Regards
Trevor

**Comment by MarkEdmondson1234** [comment]
@MilesAheadAlso ah, ok.  In that case I would recommend using Dockerfiles, which is way to have an easy way to build your environment.  The easiest way to do that I think today is using the R package https://github.com/o2r-project/containerit , which you point an example R script to and constructs the Dockerfile for you.  Make sure to use soft dependencies too, since on linux it won't auto-install those for you.

A bit of background on how the VMs, Docker etc relates to each other is here: https://cloudyr.github.io/googleComputeEngineR/articles/docker.html

In brief, you can use SSH on the VM using `gce_ssh`, but to communicate with the Docker container running the R Docker image on that VM, you need `docker_exec` or similar. Its another level of abstraction, but it does make things like this easier in the long run.

Once you have a Dockerfile, it can be built into a Docker image that this library can launch when you launch a VM.  This can be done using `docker build` but I prefer using Google build triggers: https://cloud.google.com/container-builder/docs/how-to/build-triggers

That should give you a custom Docker image you can call.  The default example above uses `rocker/r-base` but you can specify your own custom image via:

```r
gce_vm("myapp", 
             template = "r-base",
             predefined_type = "n1-standard-2",
             dynamic_image = gce_tag_container("your-dockerfile", "your-project"))
```

There are some examples of doing this on the website for other workflows. 

You can then put this into the `future_lapply` function to parrallise your job across all of the R images on multiple VMs. 

I hope the above isn't too complicated, I should perhaps add it to the example page if useful.

**Comment by MilesAheadAlso** [comment]
Very much appreciate your guidance Mark
