### ISSUE TITLE
Problem using r-base template

### ISSUE THREAD

**Issue by cpgonzal** [cloudyr/googleComputeEngineR#77]
Hi, I'm executing this code:

```
vm <- gce_vm(template="r-base", 
             name = "rbase-container", 
             predefined_type = "n1-standard-1", 
             project="project_r", zone="europe-west1-c")

#is.gce_instance(vm)

vm<-gce_ssh_setup(vm,username = "user_gce", 
                  key.pub = "/home/user_gce/.ssh/id_rsa.pub",
                  key.private = "/home/user_gce/.ssh/id_rsa" )
```

The file r-base.yaml (corresponding to this template) contains the following:
  ................
    ExecStart=/usr/bin/docker run --name=r-base \
                                  -e "R_LIBS_USER=/library/" \
                                  -v /home/gcer/library/:/library/ \
                                  --net=host \
                                  %s
    ..................

but when I run the following:
`docker_run(vm, "rocker/r-base", c("Rscript", "-e", "'write.table(data.frame(a=1, b=2),file=\"/library/outfile.csv\")'"))`
I do not see the result in /home/gcer/library/ (in fact, I do not see the expected ouput shown in the examples of docker_run() help when I execute the command)

Besides, the command 'systemctl status rbase.service' returns a fail in the start of the service:

> rbase.service - R Base
>    Loaded: loaded (/etc/systemd/system/rbase.service; static; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Tue 2017-10-17 13:51:59 UTC; 32s ago
>   Process: 1516 ExecStopPost=/usr/bin/docker rm r-base (code=exited, status=0/SUCCESS)
>   Process: 1509 ExecStop=/usr/bin/docker stop r-base (code=exited, status=0/SUCCESS)
>   Process: 1457 ExecStart=/usr/bin/docker run --name=r-base -e R_LIBS_USER=/library/ -v /home/gcer/library/:/library/ --net=host rocker/r-base (code=exited, status=2)
>   Process: 1444 ExecStartPre=/usr/share/google/dockercfg_update.sh (code=exited, status=0/SUCCESS)
>  Main PID: 1457 (code=exited, status=2)
>       CPU: 46ms
> 

Thanks in advance!

**Comment by MarkEdmondson1234** [comment]
Hi, I think this is probably due to the `/library/` folder not being present or allowed on the setup, so perhaps a bug in the `cloud-config`

I would suggest writing to another folder, or even using `googleCloudStorageR` to write the files to GCS instead (since it is also authenticated if you use `googleAuthR::gar_gce_auth()` ) - thats what I do in general instead of relying on VM instances.  Its very fast when done from within the same GCE cluster, comparable to system writes, and much more reliable.

**Comment by MarkEdmondson1234** [comment]
I changed the template to not have the library.  You can use your own `cloud-config` file to customise it yourself if you don't want to do the above.

**Comment by MarkEdmondson1234** [comment]
@cpgonzal did you get a chance to see if this solved your issue?

**Comment by cpgonzal** [comment]
Sorry, Mark, for the delay to respond. I have been working with OpenMPI in solving certain problems. However, I'm going to revisit my previous jobs using this library. Last time I checked that rocker/r-base is an image that runs R automatically when you launch a container (there is a line CMD["R"] in the dockerfile of this dockerhub image); that's probably the reason of the error in rbase.service. 
However, I haven't had time to explore the possibility to customize the cloud-config. If I get new advances trying this option, I'll comment you...

**Comment by MarkEdmondson1234** [comment]
@cpgonzal the only change made is not to write to the library folder, since that wasn't a valid file location.  If you can write it to another place it will work, I suggest writing to Google Cloud Storage using googleCloudStorageR , then you can avoid the complications of making your own cloud-config
